export enum SkillType {
  LISTENING = 'LISTENING',
  SPEAKING = 'SPEAKING',
  READING = 'READING',
  WRITING = 'WRITING',
  MIXED = 'MIXED',
}

export enum CreateMethod {
  MANUAL = 'MANUAL',
  FILE_UPLOAD = 'FILE_UPLOAD',
  EXCEL_IMPORT = 'EXCEL_IMPORT',
}

export enum ExamStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum QuestionType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  TRUE_FALSE = 'TRUE_FALSE',
  FILL_BLANK = 'FILL_BLANK',
  SHORT_ANSWER = 'SHORT_ANSWER',
  ESSAY = 'ESSAY',
  AUDIO_RESPONSE = 'AUDIO_RESPONSE',
  MATCHING = 'MATCHING',
  ORDERING = 'ORDERING',
}

export enum FileType {
  AUDIO = 'AUDIO',
  IMAGE = 'IMAGE',
  PDF = 'PDF',
  DOCUMENT = 'DOCUMENT',
  VIDEO = 'VIDEO',
}

export enum FilePurpose {
  EXAM_ORIGINAL = 'EXAM_ORIGINAL',
  ANSWER_KEY = 'ANSWER_KEY',
  LISTENING_AUDIO = 'LISTENING_AUDIO',
  QUESTION_MEDIA = 'QUESTION_MEDIA',
  READING_PASSAGE = 'READING_PASSAGE',
  STUDENT_SUBMISSION = 'STUDENT_SUBMISSION',
}
